In [2]:
#Tạo arr_zeros có 10 phần tử 0, cập nhật phần tử ở vị trí thứ 5 là 1.

import numpy as np
arr_zeros = np.zeros(10,dtype=int)
arr_zeros[4]=1
arr_zeros


array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [3]:
#Tạo arr_h có giá trị từ 10 đến 24. In danh sách các phần tử theo tứ tự đảo ngược của arr_h.
arr_h = np.arange(10,25)
new_arr_h = arr_h[::-1]
new_arr_h

array([24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

In [4]:
#tạo arr_l từ arr_k với các phầntử khác 0.
arr_k = np.array([1, 2, 0, 8, 2, 0, 1, 3, 0, 5, 0])
arr_l = arr_k[arr_k != 0]
arr_l

array([1, 2, 8, 2, 1, 3, 5])

In [5]:
#Từ arr_l của câu 3, thêm 2 phần tử có giá trị là 10 và 20 vào cuối array
new_arr_l = np.append(arr_l,[10,20])
new_arr_l

array([ 1,  2,  8,  2,  1,  3,  5, 10, 20])

In [6]:
#thêm phần tử có giá trị 100 vào vị trí có index = 5.
new_element = 100
index_to_insert = 5
new_arr_l5 = np.insert(arr_l,index_to_insert ,new_element)
new_arr_l5

array([  1,   2,   8,   2,   1, 100,   3,   5])

In [8]:
#xóa các phần tử tại vị trí có index = 0, 1, 2
idx_to_delete = [0,1,2]
new_arr_l6 = np.delete(new_arr_l5,idx_to_delete)
new_arr_l6

array([  2,   1, 100,   3,   5])