In [2]:
import numpy as np
arr = np.arange(10)
print(arr)
print('kiểu dữ liệu của arr là :',arr.dtype)
print('Kích thước của mảng là :',arr.shape)

[0 1 2 3 4 5 6 7 8 9]
kiểu dữ liệu của arr là : int64
Kích thước của mảng là : (10,)


In [6]:
arr_odd = arr[ arr%2 != 0]
arr_even = arr[ arr%2 == 0]
print(arr_odd)
print(arr_even)

[1 3 5 7 9]
[0 2 4 6 8]


In [3]:
arr_update =np.where(arr % 2 == 0, arr, 100)
#trả về các phần tử được chọn từ a hoặc b tùy thuộc vào điều kiện
print (arr_update)


[  0 100   2 100   4 100   6 100   8 100]
